version: "3.8"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: collector
    restart: unless-stopped
    
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics (internal)
      - "8889:8889"   # Prometheus exporter (metrics para Prometheus)
      - "13133:13133" # Health check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:13133/health"]
      interval: 30s
      timeout: 10s
      retries: 3
